### ISSUE TITLE
Different results from different functions

### ISSUE THREAD

**Issue by erlianggao** [jebyrnes/multifunc#14]
When calculating effective multifunctionality by multiplying the number of effective functions and average function level, I get different results from directly calculating effective multifunctionality using getMF_eff function. Below are my codes:

library(multifunc)
data("duffy_2003")
function_dist <- cor_dist(duffy_2003[,c(6:13)])#distance between functions

#number of effective funcions
num_of_eff_func <- eff_num_func(dat = duffy_2003,vars = colnames(duffy_2003[,c(6:13)]), q=1,
                                D = function_dist,tau = dmean(duffy_2003[,c(6:13)],function_dist))
#average function value
standardized_func <- getStdAndMeanFunctions(dat = duffy_2003[,c(6:13)], vars = colnames(duffy_2003[,c(6:13)]), 
                                            standardizeFunction = standardizeUnitScale)
average_func <- standardized_func$meanFunction

#products of qN and A
mf_eff1 <- num_of_eff_func * average_func

#get mf_eff directly
mf_eff2 <- getMF_eff(data = duffy_2003,vars = colnames(duffy_2003[,c(6:13)]), q=1, 
                    standardize_function = standardizeUnitScale, D = function_dist, tau = dmean(duffy_2003[,c(6:13)],function_dist))

**Comment by jebyrnes** [comment]
The problem here is that, in the first bit, you are calculating effective number of functions based on the *RAW* function values, not the standardized function values. This will cause problems as `eff_num_func()` assumed you have standardized. If you have not, the results will depend on the raw units of the function measurements, which is problematic.

**Comment by erlianggao** [comment]
Thank you VERY much!
